name: Build Docs
on:
  push:
    branches: [ main ]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: Install Doxygen
        run: sudo apt-get install doxygen -y

      - name: Generate Doxygen Docs
        run: doxygen Doxyfile

      - name: Build MkDocs Site
        run: mkdocs build --site-dir site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
